language: rust
rust    : nightly

addons:
  firefox: latest
  chrome : stable

install:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

jobs:
  include:
    - stage: "Build"
      script: cargo build
    - stage: "Test"
      name: "Cargo Tests"
      script: cargo test
    - name: "Chrome Tests"
      script: wasm-pack test --chrome  --headless
    - name: "Firefox Tests"
      script: wasm-pack test --firefox --headless
  allow_failures:
    - name: "Firefox Tests"