[package]
name = "exports"
version = "0.1.0"
authors = ["Austin Carrig <austincarrig.raspi@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.68"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"